# Generated by Django 2.2 on 2020-06-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='exotic',
            field=models.BooleanField(default='default'),
            preserve_default=False,
        ),
    ]
