# Generated by Django 2.2 on 2020-06-13 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_dish_exotic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='exotic',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
