# Generated by Django 2.2 on 2020-06-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_utensil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utensil',
            name='users',
            field=models.ManyToManyField(related_name='utensilss', to='main.Chef'),
        ),
    ]
