# Generated by Django 2.2 on 2020-06-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200613_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utensil',
            name='users',
            field=models.ManyToManyField(related_name='utensils', to='main.Chef'),
        ),
    ]
