# Generated by Django 2.2 on 2020-06-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200613_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utensil',
            name='is_sharp',
        ),
    ]
