# Generated by Django 2.2 on 2020-06-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_utensil_is_sharp'),
    ]

    operations = [
        migrations.AddField(
            model_name='utensil',
            name='is_sharp',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
