# Generated by Django 2.2 on 2020-06-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_utensil_is_sharp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utensil',
        ),
    ]
